### ISSUE TITLE
Cannot find module 'next-auth/adapters' or its corresponding type declarations.ts (2307)

### ISSUE THREAD

**Issue by ernstlegaspi** [adrianhajdin/project_nextjs13_flexibble#23]
![image](https://github.com/adrianhajdin/project_nextjs13_flexibble/assets/40289639/d6e474a1-5f47-4d9c-b647-264317261ae8)

I have this error where it says cannot find module. I installed the next-auth and it is up to date. What seems to be the problem here? Thank you so much in advance guys. Please help me

**Comment by sarbastu** [comment]
Try changing "moduleResolution" from "bundler" to "node" in tsconfig.json.

**Comment by ernstlegaspi** [comment]
Thanks @sarbastu that helped me.

**Comment by aryanarora29** [comment]
> Try changing "moduleResolution" from "bundler" to "node" in tsconfig.json.

Thanks bro , it worked!
