### ISSUE TITLE
Internal Server Error 500 in uploading image to CLOUDINARY

### ISSUE THREAD

**Issue by ValkonX33** [adrianhajdin/project_nextjs13_flexibble#37]
Facing the same Internal Server Error when adding a project to, when i checked in the networking section it shows the 500 internal server error in uploading the image to cloudinary, I've doubled checked my env files and everything but nothing seems to be working  
![image](https://github.com/adrianhajdin/project_nextjs13_flexibble/assets/77388132/693bcd6a-6ffd-4f2a-acca-5161ac7cb66b)
here's ss of my env file please someone look into this

**Comment by ahmadali3180** [comment]
hey, did you solve this?
