### ISSUE TITLE
Project is not Creating After Deploying on vercel 

### ISSUE THREAD

**Issue by ValkonX33** [adrianhajdin/project_nextjs13_flexibble#39]
i solved the authentication error by adding the one of the production deployment links in the google cloud redirect URI (because for some reason it is not taking the actual domain that has been provided by vercel its showing access denied on that, later when i moved to creating a project it showed a 308, i thought there might be something wrong with my NEXT_PUBLIC_SERVER_URL as so i changed it to the same url as the google cloud production deployment url (ex:- https://vercel.com/valkonx33/code-vault/6o37o1LxqFSGQ293tzu7oJAugPkC) 
its throwing 200 now but token is not passing 
![image](https://github.com/adrianhajdin/project_nextjs13_flexibble/assets/77388132/987249ec-da15-41e8-b551-ff9e947c38d8)

idk what i'm doing wrong but its not working i need help urgent please

**Comment by ValkonX33** [comment]
what error exactly  are you facing?

**Comment by PHANTOMGOD2OP** [comment]
Same Token Error On Creating

**Comment by PHANTOMGOD2OP** [comment]
The Post Never Gets Created Just Gets Stuck On Creating and in network Tab it shows token error

**Comment by PHANTOMGOD2OP** [comment]
https://flexibble-xi-three.vercel.app/create-project

Link to my website

**Comment by ValkonX33** [comment]
can you share you .env file formatting to me? 
just hide your keys with marker and show me how you've declared them keys
